src/main/java/mBeans/SessionBean.java
package mBeans;

import controller.ControllerInt;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import project.ProjectInt;

@ManagedBean(name = "sessionBean")
@SessionScoped
public class SessionBean implements Serializable {

    private static final long serialVersionUID = -2762117385230274461L;

    private List<ProjectInt> projects = new ArrayList<>();

    public SessionBean() {
    }

    public List<ProjectInt> getProjects() {
        return projects;
    }

    public void setProjects(List<ProjectInt> projects) {
        this.projects = projects;
    }

    public void deleteProject(ProjectInt project) {
        projects.remove(project);
    }

    public void addProject(ProjectInt project) {
        projects.add(project);
    }

    public String getUser() {
        return FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().getName();
    }

    List<ControllerInt> getControllers() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}

src/main/webapp/layouts/home.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:h="http://java.sun.com/jsf/html"  
      xmlns:f="http://java.sun.com/jsf/core"  
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">  
    <h:head>
        <title><ui:insert name="title">Название по умолчанию</ui:insert></title>
        <link rel="shortcut icon" href="#{resource['images/favicon.ico']}" />
        <h:outputStylesheet library="styles" name="style.css" />
    </h:head>
    <h:body>

        <div class="ui-g">
            <div class="ui-g-12 ui-md-12 ui-lg-12 padd" >
                <h:form >  
                    <p:tabMenu activeIndex="#{param.i}"  >
                        <p:menuitem value="Проекты"  outcome="projects"> 
                            <f:param name="i" value="0" />
                        </p:menuitem>             
                        <p:menuitem value="Контроллеры"  outcome="controllers"> 
                            <f:param name="i" value="1" />
                        </p:menuitem>
                        <p:menuitem value="Модули" outcome="modules" > 
                            <f:param name="i" value="2" />
                        </p:menuitem>   
                        <p:menuitem value="Каналы" outcome="chanels" > 
                            <f:param name="i" value="3" />
                        </p:menuitem>  
                        <p:menuitem value="Iec 104" outcome="iec">
                            <f:param name="i" value="4" />
                        </p:menuitem>    
                        <p:menuitem value="Экспорт конфигурации" outcome="export">
                            <f:param name="i" value="5" />
                        </p:menuitem>     
                        <p:menuitem value="Конвертер" outcome="convert">
                            <f:param name="i" value="6" />
                        </p:menuitem>
                        <p:menuitem value="Выход" action="#{loginBean.logout()}" >

                        </p:menuitem>
                    </p:tabMenu>            
                </h:form>   
            </div>
        </div>

        <div class="ui-g">
            <div class="ui-g-12 ui-md-12 ui-lg-12">
                <ui:insert name="content">Содержимое по умолчанию</ui:insert>   
            </div>
        </div>
        <p:separator /> 
        <div class="ui-g">
            <div class="ui-g-12 ui-md-12 ui-lg-12">
                <div class="ui-g-12 ui-md-2 ui-lg-2"><h:graphicImage  library="images" name="tecon_logo.png"/></div>
                <div class="ui-g-12 ui-md-2 ui-lg-2">#{sessionBean.user}</div>
                
            </div>
        </div>
    </h:body>
</html>   


src/main/webapp/layouts/start.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:h="http://java.sun.com/jsf/html"  
      xmlns:f="http://java.sun.com/jsf/core"  
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">  
    <h:head>
        <title><ui:insert name="title">Название по умолчанию</ui:insert></title>
        <link rel="shortcut icon" href="#{resource['images/favicon.ico']}" />
        <h:outputStylesheet library="css" name="style.css" />
    </h:head>
    <h:body>
        <div class="ui-g" id="container">
            <ui:insert name="content">Содержимое по умолчанию</ui:insert>  
        </div>
    </h:body>
</html>   
